### ISSUE TITLE
How to install mod_jk more easily

### ISSUE THREAD

**Issue by micro-xl** [jinkyuhan/CDP2_WAS_clustering#10]
#5 How to install mod_jk more easily
Check to replace 'apt-get install libapache2-mod-jk' with 'wget' and 'make'

**Comment by cheesecat47** [comment]
refer to this site: https://all-record.tistory.com/188

**Comment by micro-xl** [comment]
해당 레퍼런스는 우분투 기반으로 쓰여져서 apt-get install libapache2-mod-jk 방식으로 설치합니다.
이 경우 apache2의 경로는 /etc/apache2/ 입니다.
하지만 이 프로젝트에서 apache-server의 기반 이미지인 httpd:2.4의 경우 기본적으로 apache2 의 경로가 /usr/local/apache2로 되어있습니다.

확인한 결과, 컨테이너 안에서 'apt-get install libapache2-mod-jk'를 수행할 경우 /usr/local/apache2/modules 안에 jk모듈이 설치 되지 않습니다. 이는 경로가 다르기 때문입니다. **즉, 이는 로컬환경에선 정상적으로 작동하지만, 이 프로젝트의 Docker container 위에서는 정상적으로 기능하지 않습니다.**

따라서 이 프로젝트의 CDP2_WAS_clustering/apache_src/Dockerfile 에 쓰여진 것 처럼 http://apache.tt.co.kr/tomcat/tomcat-connectors/jk/tomcat-connectors-1.2.48-src.tar.gz 로부터 다운받은 파일을 make하여 사용하는 것이 바람직한 것으로 보입니다.
