### ISSUE TITLE
tomcat configuration

### ISSUE THREAD

**Issue by micro-xl** [jinkyuhan/CDP2_WAS_clustering#14]
#5 
현재 mod_jk를 통한 연동 시도 시 Service Unavailable (503) 뜨는 원인이
Tomcat의 일부 설정에 있는 듯 함.
관련 설정 필요.

**Comment by cheesecat47** [comment]
https://goddaehee.tistory.com/77

**Comment by cheesecat47** [comment]
https://nirsa.tistory.com/131

**Comment by cheesecat47** [comment]
https://www.kangtaeho.com/55

**Comment by micro-xl** [comment]
apache/worker의 host name설정,
tomcat/server.xml의 set AJP connector ip address 0.0.0.0, set secretRequired="true" 
통해서 해결
