### ISSUE TITLE
Build fail for apache-server

### ISSUE THREAD

**Issue by micro-xl** [jinkyuhan/CDP2_WAS_clustering#20]
apache-src/Dockerfile

./configure  ERROR

ERROR: Service 'httpd' failed to build: The command '/bin/sh -c cd ./tomcat-connectors-1.2.48-src/native/ &&     ./configure --with-apxs=/usr/local/apache2/bin/apxs &&     make &&     make install' returned a non-zero code: 127

**Comment by cheesecat47** [comment]
connector를 매번 wget으로 받을 필요가 없는 것 같아서 다운 받은 후 압축을 풀고, 폴더를 컨테이너로 COPY하는 방법으로 바꿨는데, 이 때 configure 파일이 .gitignore에 걸려서 복사가 안된게 아닐까 추측함.
압축파일 풀지 않고 컨테이너로 복사한 후 컨테이너 안에서 압축 푸는 방법으로 변경.
