### ISSUE TITLE
Make Containers

### ISSUE THREAD

**Issue by micro-xl** [jinkyuhan/CDP2_WAS_clustering#4]
Docker-compose 를 이용해 다중 컨테이너환경 구성

**Comment by micro-xl** [comment]
https://www.44bits.io/ko/post/almost-perfect-development-environment-with-docker-and-docker-compose

Docker compose 적용시 별도의 스크립트 필요없음

**Comment by cheesecat47** [comment]
docker-compose파일 속성값
https://docs.docker.com/compose/compose-file/ 

톰캣 도커
https://hub.docker.com/_/tomcat
https://bluedayj.tistory.com/75?category=846891
