### ISSUE TITLE
Connect Apache to Tomcat in Docker container

### ISSUE THREAD

**Issue by micro-xl** [jinkyuhan/CDP2_WAS_clustering#5]
apache와 tomcat 연동하기

**Comment by cheesecat47** [comment]
httpd.conf
https://www.opentutorials.org/module/3923/23838

**Comment by micro-xl** [comment]
https://wikidocs.net/16277
jk모듈 이용한 아파치 톰캣 연동

**Comment by micro-xl** [comment]
Resolved
