### ISSUE TITLE
tomcat-server 404 problem

### ISSUE THREAD

**Issue by atg0831** [jinkyuhan/CDP2_WAS_clustering#9]
http 404 response is due to the default webapps being removed

**Comment by atg0831** [comment]
참고 : https://github.com/docker-library/tomcat/issues/184

**Comment by micro-xl** [comment]
/usr/local/tomcat/webapps.dist/ 안의 쓸모 있어 보이는 모든 파일들을 /usr/local/tomcat/webapps/ 로 이동하는 내용을 tomcat_src/Dockerfile에 추가함으로 해결.
